[toolchain]
anchor_version = "1.0.2"

[features]
resolution = true
skip-lint = false

[programs.localnet]
safepump_core = "FMAhGG8ETyqnd4zan4HBdLRPEQvk7Cvc6kzWbsvnXj5q"

[programs.devnet]
safepump_core = "FMAhGG8ETyqnd4zan4HBdLRPEQvk7Cvc6kzWbsvnXj5q"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[test.validator]
rpc_port = 8900
faucet_port = 9901

[scripts]
test = "npm run test:ts"
